### ISSUE TITLE
[Mac] create Python module failed

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#225]
OS : Mac 10.13
Edge:1.2.0.-rc2

1.create new python module 

Command failed with exit code 1

Executing cookiecutter --no-input https://github.com/Azure/cookiecutter-azure-iot-edge-module module_name=SampleModulePython05 image_repository=localhost:5000/samplemodulepython05 --checkout master
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cookiecutter/main.py", line 87, in cookiecutter
    dump(config_dict['replay_dir'], template_name, context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cookiecutter/replay.py", line 37, in dump
    with open(replay_file, 'w') as outfile:
IOError: [Errno 13] Permission denied: u'/Users/vsc/.cookiecutter_replay/cookiecutter-azure-iot-edge-module.json'
Error: Command failed with exit code 1

**Comment by LazarusX** [comment]
Please `sudo -rf /Users/vsc/.cookiecutter_replay/` and try again, and be sure **not** to open VS Code with `sudo` in the future.

**Comment by czgtest** [comment]
after delete .cookiecutter_replay ,  the python solution can create now,  it is mac envirment issue,  so close it
